import { access, readFile } from "node:fs/promises";

const requiredFiles = [
  "tide-deploy/index.html",
  "tide-deploy/site.webmanifest",
  "tide-deploy/favicon.svg",
];

for (const file of requiredFiles) {
  await access(file);
}

const html = await readFile("tide-deploy/index.html", "utf8");
const requiredSnippets = [
  "const langSeq=['en','ru','ua','es']",
  "'loc-label':    'Hora local'",
  "new Intl.DateTimeFormat",
  "timeZone: 'America/New_York'",
  "id=\"score-beacon\" cx=\"180\" cy=\"180\" r=\"13\"",
  "id=\"motion-btn\"",
  "data-i18n=\"data-updated\"",
  "NOAA data · updated 04:00",
  "const DEFAULT_LOCATION = {",
  "stationId: '8661070'",
  "const NOAA_API = 'https://api.tidesandcurrents.noaa.gov/api/prod/datagetter'",
  "const NOAA_MDAPI = 'https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations.json'",
  "const APP_VERSION = '2026.05.26.2'",
  "APP v${APP_VERSION}",
  "function renderFooter()",
  "let activeLocation = { ...DEFAULT_LOCATION }",
  "function fetchStationCatalog()",
  "navigator.geolocation.getCurrentPosition",
  "MAX_STATION_DISTANCE_KM = 120",
  "product: 'water_level'",
  "product: 'predictions'",
  "interval: 'hilo'",
  "function walkWindowForLow(lowTime)",
  "lowTime.getTime() - 90 * 60000",
  "lowTime.getTime() + 90 * 60000",
  "function nextWalkLow(hilo, currentTime)",
  "async function refreshLiveData()",
  "class=\"wx-stage\"",
  "id=\"wx-rain\"",
  "body[data-weather=\"storm\"] .wx-clouds",
  "body.motion-on[data-weather=\"storm\"] .wx-lightning",
  "function generateStars()",
  "const RainEngine = (function()",
  "window.setWeatherVisual = function setWeatherVisual(state)",
  "grid-template-areas:\"place side\"",
  "position:absolute;left:50%;top:36px;transform:translateX(-50%)",
  "grid metrics-panel",
  "display:flex;flex-direction:column;gap:8px;flex:0 0 auto",
  "score-hero",
  "metrics-factors",
  ".score-number #score-value{font-size:clamp(58px,17vw,76px)",
  ".walk-time{font-size:clamp(23px,7vw,30px)",
  ".metric-value.wind-value{display:flex",
  "display:flex;align-items:center;gap:6px;color:var(--text)",
  ".loc-name{",
  "max-width:230px;overflow:hidden;text-overflow:ellipsis",
  ".wx-temp{font-size:25px",
  "transform-origin:180px 180px",
  "score-main caution",
  "metric-item safe",
  "card.className = `score-main ${band.cls}`",
  "const scoreColor = value ? getComputedStyle(value).color : band.color",
  "'tide-walk-score':'Current walk rating'",
  "'tide-walk-score':'Рейтинг текущей прогулки'",
  "'tide-walk-score':'Рейтинг поточної прогулянки'",
  "'tide-walk-score':'Rating del paseo actual'",
  "'walk-window':  'Best walk window'",
  "'walk-window':  'Лучшее окно для прогулки'",
  "'walk-window':  'Найкраще вікно для прогулянки'",
  "'walk-window':  'Mejor ventana para caminar'",
  "'next-high':    'Next high'",
  "'next-high':    'Следующий прилив'",
  "'next-high':    'Наступний приплив'",
  "'next-high':    'Próxima pleamar'",
  "'val-wind-dir': 'S'",
  "'val-wind-speed':'10–15'",
  "'location-use':  'Use my location'",
  "data-i18n=\"walk-time-value\"",
  "data-i18n=\"next-tide-time\"",
  "id=\"location-btn\"",
  "id=\"location-status\"",
  "body.motion-on #score-beacon",
  "body.motion-on .wave1",
  "body.classList.add('motion-on')",
  "body.classList.remove('motion-on')",
  "function startMotion()",
  "function stopMotion()",
  "let motionEnabled = false",
  "const fps = isMobile ? 24 : 30",
  "ctx.beginPath()",
  "ctx.stroke()",
  "body.motion-on .grid.metrics-panel",
  "--glass:rgba(8,18,36,.88)",
];

for (const snippet of requiredSnippets) {
  if (!html.includes(snippet)) {
    throw new Error(`Missing deploy snippet: ${snippet}`);
  }
}

console.log("Deploy files look ready.");
